name: logic_conf
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  win32: ^2.0.0
  ffi: ^1.1.0

dev_dependencies:
  pedantic: ^1.10.0
  ffigen: ^3.0.0
