// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `hidsdi.h`.
class HidSdi {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  HidSdi(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  HidSdi.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int HidP_GetCaps(
    ffi.Pointer<PHIDP_PREPARSED_DATA> PreparsedData,
    ffi.Pointer<PHIDP_CAPS> Capabilities,
  ) {
    return _HidP_GetCaps(
      PreparsedData,
      Capabilities,
    );
  }

  late final _HidP_GetCaps_ptr =
      _lookup<ffi.NativeFunction<_c_HidP_GetCaps>>('HidP_GetCaps');
  late final _dart_HidP_GetCaps _HidP_GetCaps =
      _HidP_GetCaps_ptr.asFunction<_dart_HidP_GetCaps>();

  int HidD_GetAttributes(
    ffi.Pointer<ffi.Void> HidDeviceObject,
    ffi.Pointer<PHIDD_ATTRIBUTES> Attributes,
  ) {
    return _HidD_GetAttributes(
      HidDeviceObject,
      Attributes,
    );
  }

  late final _HidD_GetAttributes_ptr =
      _lookup<ffi.NativeFunction<_c_HidD_GetAttributes>>('HidD_GetAttributes');
  late final _dart_HidD_GetAttributes _HidD_GetAttributes =
      _HidD_GetAttributes_ptr.asFunction<_dart_HidD_GetAttributes>();

  int HidD_GetPreparsedData(
    ffi.Pointer<ffi.Void> HidDeviceObject,
    ffi.Pointer<ffi.Pointer<PHIDP_PREPARSED_DATA>> PreparsedData,
  ) {
    return _HidD_GetPreparsedData(
      HidDeviceObject,
      PreparsedData,
    );
  }

  late final _HidD_GetPreparsedData_ptr =
      _lookup<ffi.NativeFunction<_c_HidD_GetPreparsedData>>(
          'HidD_GetPreparsedData');
  late final _dart_HidD_GetPreparsedData _HidD_GetPreparsedData =
      _HidD_GetPreparsedData_ptr.asFunction<_dart_HidD_GetPreparsedData>();

  int HidD_FreePreparsedData(
    ffi.Pointer<PHIDP_PREPARSED_DATA> PreparsedData,
  ) {
    return _HidD_FreePreparsedData(
      PreparsedData,
    );
  }

  late final _HidD_FreePreparsedData_ptr =
      _lookup<ffi.NativeFunction<_c_HidD_FreePreparsedData>>(
          'HidD_FreePreparsedData');
  late final _dart_HidD_FreePreparsedData _HidD_FreePreparsedData =
      _HidD_FreePreparsedData_ptr.asFunction<_dart_HidD_FreePreparsedData>();
}

class PHIDP_PREPARSED_DATA extends ffi.Opaque {}

class PHIDP_CAPS extends ffi.Struct {
  @ffi.Uint16()
  external int Usage;

  @ffi.Uint16()
  external int UsagePage;

  @ffi.Uint16()
  external int InputReportByteLength;

  @ffi.Uint16()
  external int OutputReportByteLength;

  @ffi.Uint16()
  external int FeatureReportByteLength;

  @ffi.Array.multi([17])
  external ffi.Array<ffi.Uint16> Reserved;

  @ffi.Uint16()
  external int NumberLinkCollectionNodes;

  @ffi.Uint16()
  external int NumberInputButtonCaps;

  @ffi.Uint16()
  external int NumberInputValueCaps;

  @ffi.Uint16()
  external int NumberInputDataIndices;

  @ffi.Uint16()
  external int NumberOutputButtonCaps;

  @ffi.Uint16()
  external int NumberOutputValueCaps;

  @ffi.Uint16()
  external int NumberOutputDataIndices;

  @ffi.Uint16()
  external int NumberFeatureButtonCaps;

  @ffi.Uint16()
  external int NumberFeatureValueCaps;

  @ffi.Uint16()
  external int NumberFeatureDataIndices;
}

class PHIDD_ATTRIBUTES extends ffi.Struct {
  @ffi.Uint32()
  external int Size;

  @ffi.Uint16()
  external int VendorID;

  @ffi.Uint16()
  external int ProductID;

  @ffi.Uint16()
  external int VersionNumber;
}

const int HIDP_STATUS_SUCCESS = 1114112;

typedef _c_HidP_GetCaps = ffi.Int32 Function(
  ffi.Pointer<PHIDP_PREPARSED_DATA> PreparsedData,
  ffi.Pointer<PHIDP_CAPS> Capabilities,
);

typedef _dart_HidP_GetCaps = int Function(
  ffi.Pointer<PHIDP_PREPARSED_DATA> PreparsedData,
  ffi.Pointer<PHIDP_CAPS> Capabilities,
);

typedef _c_HidD_GetAttributes = ffi.Uint8 Function(
  ffi.Pointer<ffi.Void> HidDeviceObject,
  ffi.Pointer<PHIDD_ATTRIBUTES> Attributes,
);

typedef _dart_HidD_GetAttributes = int Function(
  ffi.Pointer<ffi.Void> HidDeviceObject,
  ffi.Pointer<PHIDD_ATTRIBUTES> Attributes,
);

typedef _c_HidD_GetPreparsedData = ffi.Uint8 Function(
  ffi.Pointer<ffi.Void> HidDeviceObject,
  ffi.Pointer<ffi.Pointer<PHIDP_PREPARSED_DATA>> PreparsedData,
);

typedef _dart_HidD_GetPreparsedData = int Function(
  ffi.Pointer<ffi.Void> HidDeviceObject,
  ffi.Pointer<ffi.Pointer<PHIDP_PREPARSED_DATA>> PreparsedData,
);

typedef _c_HidD_FreePreparsedData = ffi.Uint8 Function(
  ffi.Pointer<PHIDP_PREPARSED_DATA> PreparsedData,
);

typedef _dart_HidD_FreePreparsedData = int Function(
  ffi.Pointer<PHIDP_PREPARSED_DATA> PreparsedData,
);
