// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `libudev.h`.
class Libudev {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  Libudev(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  ffi.Pointer<udev> udev_unref(
    ffi.Pointer<udev> udev,
  ) {
    return (_udev_unref ??=
        _dylib.lookupFunction<_c_udev_unref, _dart_udev_unref>('udev_unref'))(
      udev,
    );
  }

  _dart_udev_unref? _udev_unref;

  ffi.Pointer<udev> udev_new() {
    return (_udev_new ??=
        _dylib.lookupFunction<_c_udev_new, _dart_udev_new>('udev_new'))();
  }

  _dart_udev_new? _udev_new;

  ffi.Pointer<udev_list_entry> udev_list_entry_get_next(
    ffi.Pointer<udev_list_entry> list_entry,
  ) {
    return (_udev_list_entry_get_next ??= _dylib.lookupFunction<
        _c_udev_list_entry_get_next,
        _dart_udev_list_entry_get_next>('udev_list_entry_get_next'))(
      list_entry,
    );
  }

  _dart_udev_list_entry_get_next? _udev_list_entry_get_next;

  ffi.Pointer<ffi.Int8> udev_list_entry_get_name(
    ffi.Pointer<udev_list_entry> list_entry,
  ) {
    return (_udev_list_entry_get_name ??= _dylib.lookupFunction<
        _c_udev_list_entry_get_name,
        _dart_udev_list_entry_get_name>('udev_list_entry_get_name'))(
      list_entry,
    );
  }

  _dart_udev_list_entry_get_name? _udev_list_entry_get_name;

  ffi.Pointer<udev_device> udev_device_unref(
    ffi.Pointer<udev_device> udev_device,
  ) {
    return (_udev_device_unref ??=
        _dylib.lookupFunction<_c_udev_device_unref, _dart_udev_device_unref>(
            'udev_device_unref'))(
      udev_device,
    );
  }

  _dart_udev_device_unref? _udev_device_unref;

  ffi.Pointer<udev_device> udev_device_new_from_syspath(
    ffi.Pointer<udev> udev,
    ffi.Pointer<ffi.Int8> syspath,
  ) {
    return (_udev_device_new_from_syspath ??= _dylib.lookupFunction<
        _c_udev_device_new_from_syspath,
        _dart_udev_device_new_from_syspath>('udev_device_new_from_syspath'))(
      udev,
      syspath,
    );
  }

  _dart_udev_device_new_from_syspath? _udev_device_new_from_syspath;

  ffi.Pointer<udev_device> udev_device_get_parent_with_subsystem_devtype(
    ffi.Pointer<udev_device> udev_device,
    ffi.Pointer<ffi.Int8> subsystem,
    ffi.Pointer<ffi.Int8> devtype,
  ) {
    return (_udev_device_get_parent_with_subsystem_devtype ??=
        _dylib.lookupFunction<_c_udev_device_get_parent_with_subsystem_devtype,
                _dart_udev_device_get_parent_with_subsystem_devtype>(
            'udev_device_get_parent_with_subsystem_devtype'))(
      udev_device,
      subsystem,
      devtype,
    );
  }

  _dart_udev_device_get_parent_with_subsystem_devtype?
      _udev_device_get_parent_with_subsystem_devtype;

  ffi.Pointer<ffi.Int8> udev_device_get_devnode(
    ffi.Pointer<udev_device> udev_device,
  ) {
    return (_udev_device_get_devnode ??= _dylib.lookupFunction<
        _c_udev_device_get_devnode,
        _dart_udev_device_get_devnode>('udev_device_get_devnode'))(
      udev_device,
    );
  }

  _dart_udev_device_get_devnode? _udev_device_get_devnode;

  ffi.Pointer<ffi.Int8> udev_device_get_sysattr_value(
    ffi.Pointer<udev_device> udev_device,
    ffi.Pointer<ffi.Int8> sysattr,
  ) {
    return (_udev_device_get_sysattr_value ??= _dylib.lookupFunction<
        _c_udev_device_get_sysattr_value,
        _dart_udev_device_get_sysattr_value>('udev_device_get_sysattr_value'))(
      udev_device,
      sysattr,
    );
  }

  _dart_udev_device_get_sysattr_value? _udev_device_get_sysattr_value;

  ffi.Pointer<udev_enumerate> udev_enumerate_unref(
    ffi.Pointer<udev_enumerate> udev_enumerate,
  ) {
    return (_udev_enumerate_unref ??= _dylib.lookupFunction<
        _c_udev_enumerate_unref,
        _dart_udev_enumerate_unref>('udev_enumerate_unref'))(
      udev_enumerate,
    );
  }

  _dart_udev_enumerate_unref? _udev_enumerate_unref;

  ffi.Pointer<udev_enumerate> udev_enumerate_new(
    ffi.Pointer<udev> udev,
  ) {
    return (_udev_enumerate_new ??=
        _dylib.lookupFunction<_c_udev_enumerate_new, _dart_udev_enumerate_new>(
            'udev_enumerate_new'))(
      udev,
    );
  }

  _dart_udev_enumerate_new? _udev_enumerate_new;

  int udev_enumerate_add_match_subsystem(
    ffi.Pointer<udev_enumerate> udev_enumerate,
    ffi.Pointer<ffi.Int8> subsystem,
  ) {
    return (_udev_enumerate_add_match_subsystem ??= _dylib.lookupFunction<
            _c_udev_enumerate_add_match_subsystem,
            _dart_udev_enumerate_add_match_subsystem>(
        'udev_enumerate_add_match_subsystem'))(
      udev_enumerate,
      subsystem,
    );
  }

  _dart_udev_enumerate_add_match_subsystem? _udev_enumerate_add_match_subsystem;

  int udev_enumerate_scan_devices(
    ffi.Pointer<udev_enumerate> udev_enumerate,
  ) {
    return (_udev_enumerate_scan_devices ??= _dylib.lookupFunction<
        _c_udev_enumerate_scan_devices,
        _dart_udev_enumerate_scan_devices>('udev_enumerate_scan_devices'))(
      udev_enumerate,
    );
  }

  _dart_udev_enumerate_scan_devices? _udev_enumerate_scan_devices;

  ffi.Pointer<udev_list_entry> udev_enumerate_get_list_entry(
    ffi.Pointer<udev_enumerate> udev_enumerate,
  ) {
    return (_udev_enumerate_get_list_entry ??= _dylib.lookupFunction<
        _c_udev_enumerate_get_list_entry,
        _dart_udev_enumerate_get_list_entry>('udev_enumerate_get_list_entry'))(
      udev_enumerate,
    );
  }

  _dart_udev_enumerate_get_list_entry? _udev_enumerate_get_list_entry;
}

class udev extends ffi.Opaque {}

class udev_list_entry extends ffi.Opaque {}

class udev_device extends ffi.Opaque {}

class udev_enumerate extends ffi.Opaque {}

typedef _c_udev_unref = ffi.Pointer<udev> Function(
  ffi.Pointer<udev> udev,
);

typedef _dart_udev_unref = ffi.Pointer<udev> Function(
  ffi.Pointer<udev> udev,
);

typedef _c_udev_new = ffi.Pointer<udev> Function();

typedef _dart_udev_new = ffi.Pointer<udev> Function();

typedef _c_udev_list_entry_get_next = ffi.Pointer<udev_list_entry> Function(
  ffi.Pointer<udev_list_entry> list_entry,
);

typedef _dart_udev_list_entry_get_next = ffi.Pointer<udev_list_entry> Function(
  ffi.Pointer<udev_list_entry> list_entry,
);

typedef _c_udev_list_entry_get_name = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<udev_list_entry> list_entry,
);

typedef _dart_udev_list_entry_get_name = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<udev_list_entry> list_entry,
);

typedef _c_udev_device_unref = ffi.Pointer<udev_device> Function(
  ffi.Pointer<udev_device> udev_device,
);

typedef _dart_udev_device_unref = ffi.Pointer<udev_device> Function(
  ffi.Pointer<udev_device> udev_device,
);

typedef _c_udev_device_new_from_syspath = ffi.Pointer<udev_device> Function(
  ffi.Pointer<udev> udev,
  ffi.Pointer<ffi.Int8> syspath,
);

typedef _dart_udev_device_new_from_syspath = ffi.Pointer<udev_device> Function(
  ffi.Pointer<udev> udev,
  ffi.Pointer<ffi.Int8> syspath,
);

typedef _c_udev_device_get_parent_with_subsystem_devtype
    = ffi.Pointer<udev_device> Function(
  ffi.Pointer<udev_device> udev_device,
  ffi.Pointer<ffi.Int8> subsystem,
  ffi.Pointer<ffi.Int8> devtype,
);

typedef _dart_udev_device_get_parent_with_subsystem_devtype
    = ffi.Pointer<udev_device> Function(
  ffi.Pointer<udev_device> udev_device,
  ffi.Pointer<ffi.Int8> subsystem,
  ffi.Pointer<ffi.Int8> devtype,
);

typedef _c_udev_device_get_devnode = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<udev_device> udev_device,
);

typedef _dart_udev_device_get_devnode = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<udev_device> udev_device,
);

typedef _c_udev_device_get_sysattr_value = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<udev_device> udev_device,
  ffi.Pointer<ffi.Int8> sysattr,
);

typedef _dart_udev_device_get_sysattr_value = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<udev_device> udev_device,
  ffi.Pointer<ffi.Int8> sysattr,
);

typedef _c_udev_enumerate_unref = ffi.Pointer<udev_enumerate> Function(
  ffi.Pointer<udev_enumerate> udev_enumerate,
);

typedef _dart_udev_enumerate_unref = ffi.Pointer<udev_enumerate> Function(
  ffi.Pointer<udev_enumerate> udev_enumerate,
);

typedef _c_udev_enumerate_new = ffi.Pointer<udev_enumerate> Function(
  ffi.Pointer<udev> udev,
);

typedef _dart_udev_enumerate_new = ffi.Pointer<udev_enumerate> Function(
  ffi.Pointer<udev> udev,
);

typedef _c_udev_enumerate_add_match_subsystem = ffi.Int32 Function(
  ffi.Pointer<udev_enumerate> udev_enumerate,
  ffi.Pointer<ffi.Int8> subsystem,
);

typedef _dart_udev_enumerate_add_match_subsystem = int Function(
  ffi.Pointer<udev_enumerate> udev_enumerate,
  ffi.Pointer<ffi.Int8> subsystem,
);

typedef _c_udev_enumerate_scan_devices = ffi.Int32 Function(
  ffi.Pointer<udev_enumerate> udev_enumerate,
);

typedef _dart_udev_enumerate_scan_devices = int Function(
  ffi.Pointer<udev_enumerate> udev_enumerate,
);

typedef _c_udev_enumerate_get_list_entry = ffi.Pointer<udev_list_entry>
    Function(
  ffi.Pointer<udev_enumerate> udev_enumerate,
);

typedef _dart_udev_enumerate_get_list_entry = ffi.Pointer<udev_list_entry>
    Function(
  ffi.Pointer<udev_enumerate> udev_enumerate,
);
