// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to `CoreFoundation.h`.
class CoreFoundation {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  CoreFoundation(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  void CFRelease(
    ffi.Pointer<ffi.Void> cf,
  ) {
    return (_CFRelease ??=
        _dylib.lookupFunction<_c_CFRelease, _dart_CFRelease>('CFRelease'))(
      cf,
    );
  }

  _dart_CFRelease? _CFRelease;
}

typedef _c_CFRelease = ffi.Void Function(
  ffi.Pointer<ffi.Void> cf,
);

typedef _dart_CFRelease = void Function(
  ffi.Pointer<ffi.Void> cf,
);
