name: Main

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.4.0
      - run: |
          flutter pub get
          flutter pub run bin/k380_conf.dart

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.4.0
      - run: |
          flutter pub get
          flutter pub run bin/k380_conf.dart
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.4.0
      - run: |
          flutter pub get
          flutter pub run bin/k380_conf.dart
